version: "3"
networks:
  news:
services:
  news-adapter:
    build: ./adapter-service-layer
    ports:
      - 9000:8000
    networks:
      - news
  news-business-logic:
    build: ./business-logic-layer
    depends_on:
      - news-adapter
    ports:
      - 9001:8000
    networks:
      - news