version: "3"
networks:
  sde:
    external: true
services:
  news-adapter:
    build: ./adapter-service-layer
    ports:
      - 9000:8000
    networks:
      - sde
  news-business-logic:
    build: ./business-logic-layer
    depends_on:
      - news-adapter
    ports:
      - 9001:8000
    networks:
      - sde
  news-process-centric:
    build: ./process-centric-layer
    depends_on:
      - news-business-logic
    ports:
      - 9002:8000
    networks:
      - sde
